### ISSUE TITLE
hope to see your progress

### ISSUE THREAD

**Issue by ruiguo-bio** [Gaarv/kadenze-dl#1]
Hi! I'm looking for some tool to download kadenze video. I hope to see your progress!

**Comment by Gaarv** [comment]
Hi, thanks for your interest and sorry for the delay :) I committed a public working version of the application, I just need to add setup.py and PyPI package as weel as minimum packages requirements.

It still in early stage, so tell me if you run into any issue.

**Comment by Gaarv** [comment]
A finalized, working version has been commited. Support multiple courses and downloads are parallelized.
Tested on 3 courses. Enjoy !
