### ISSUE TITLE
App doesn't go pass login

### ISSUE THREAD

**Issue by nelsonvassalo** [Gaarv/kadenze-dl#11]
As of yesterday it seems this has stopped working. Any info on possible block from Kadenze?

**Comment by Gaarv** [comment]
I don't have noticed any major change. In fact, I just pushed some changes this morning and was able to download videos just fine. I tried just now and still working.

The script just act as a normal browser, can you login into Kadenze with a browser ?

**Comment by nelsonvassalo** [comment]
I'm logged in as I try to run it on macOS 10.13 Terminal and this is how it'r surring right now…
![kandenze-dl](https://user-images.githubusercontent.com/5526335/49741089-89f62b80-fc8d-11e8-8c78-8356379ce9d4.gif)

**Comment by nelsonvassalo** [comment]
Ah! It's working now. I think it's related to course URL's. Somehow I was getting the previous name of a course and now it's been updated to 'I'. Once I put that in, it's downloading again. Sorry for the trouble.

**Comment by Gaarv** [comment]
No problem ! With a change I made last month, unless theres a bad redirect from the site, the app should be able to automatically infer the name if you haven't updated since.
