### ISSUE TITLE
python-slugify missing from requirements.txt

### ISSUE THREAD

**Issue by crypdick** [Gaarv/kadenze-dl#12]
Program throws an exception when first installed due to missing `slugify` dependency in `requirements.txt`. After, I naively pip installed `slugify` when the actual dependency was `python-slugify`, which caused other exceptions. I'd be happy to submit a PR if you want.

**Comment by Gaarv** [comment]
Thanks for the info, it might have been a couple of updates since I last checked the whole env ! I'm abroad for a week vacation right now but will definitly look into it when I return :)

**Comment by Gaarv** [comment]
I originally read that from my cell phone so maybe I misunderstood the issue at first.

The python-slugify requirement is present in the file since june 2018, so if cloned fro master it should be there :) I made a fresh virtual env and had no issue on Linux or Windows.

**Comment by Gaarv** [comment]
Apologies for the issue. The python-slugify dependency was in fact present in requirements.txt (june 2018) but missing in setup.py.
