### ISSUE TITLE
pip3 and python3 commands examples

### ISSUE THREAD

**Issue by fguillen** [Gaarv/kadenze-dl#24]
I suggest to update the README to add examples of how to use the commands when your commands are pip3 and python3

I was very close to give up thinking there was a bug or something until I tried the *3 version of the commands.

Basically are 2 changes: 

    pip3 install -U .
    python3 kadenze-dl.py

**Comment by Gaarv** [comment]
Those are usually linked to pip / python but you're right, since only python3 is supported, might as well use it directly.
I updated the README.
