### ISSUE TITLE
Access to videos in Sessions > 10

### ISSUE THREAD

**Issue by bullpencatcher** [Gaarv/kadenze-dl#26]
Hello,

I have managed to get this to work pretty well except for one thing... I am trying to download from a course with 11 sessions total. The first 10 download just fine, but the 11th session doesn't. The first 10 are all that initially appear in the browser so I imagine that has something to do with it, but I am not sure how to modify the code to get to the second list page of sessions that contains the 11th session. Any advice is greatly appreciated.

Bryan

**Comment by Gaarv** [comment]
Hey sure, I will take a look into it. It happens that some courses are manually edited from instructors and hence doesn't follow the expected structure. Would you have the course name, see if I can run against it ?

**Comment by bullpencatcher** [comment]
Thanks. Here’s the course name:

introduction-to-programming-for-the-visual-arts-with-p5-js-vi

Bryan

**Comment by Gaarv** [comment]
Tried the course, I see what you meant now.
Sessions seems to be paginated (ie. page 1 of 2) when there"s more than 10 sessions.
I should be able to work on this week, I will let you know when it's fixed.

**Comment by Gaarv** [comment]
I'm having unusual issues with this course, when other works fine, so this is going to take a little more time.

**Comment by bullpencatcher** [comment]
No problem. I was able to find the so files and download directly through the browser, so no rush for me. Thanks for the work on this.

**Comment by Gaarv** [comment]
Should you have the need in the future, sessions > 10 should work fine now. Wasn't able to test the whole course because i requires premium access thought. I had some issues because some dependencies needed to be updated :)
