### ISSUE TITLE
H264 360p 

### ISSUE THREAD

**Issue by dorjeduck** [Gaarv/kadenze-dl#3]
This works great, thank you so much.
 
I would suggest that you offer the download of H264 360p videos instead of 720p as an option in the configuration file. 
(I just changed from 720p to 360p in the file helpers.py yet it might be useful for some). 

Thanks again

**Comment by Gaarv** [comment]
Thanks :)

Indeed, I didn't thought of that because I was just focused on HD videos, but it would be handy to have smaller ones and plus, with a so simple change.

I added the option in the configuration file and tested it, the application has been updated.
