### ISSUE TITLE
no download, pls help!

### ISSUE THREAD

**Issue by lymanzhang** [Gaarv/kadenze-dl#4]
thank you for the great tool!

I tried the script, and the terminal pops information as follows.

......
```
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ python kadenze-dl.py
Signing in www.kadenze.com ...
Parsing course: machine-learning-for-musicians-and-artists-v
Parsing course: creative-applications-of-deep-learning-with-tensorflow-iv
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ 
```

But no any download happens, it seems the script stop to run.
I just wonder what's wrong with me.

**Comment by Gaarv** [comment]
Did you installed needed requirements ? Also make sure you're using python3

pip install -r requirements.txt

**Comment by lymanzhang** [comment]
the system failed to install lxml version 3.6.4. So I install lxml version 3.7.3 instead. 
I'm not sure it is the reason.

**Comment by lymanzhang** [comment]
I changed to my another MAC Pro to run the script. The installation of requirements is OK.

```
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ pip install -r requirements.txt
Requirement already satisfied: requests==2.10.0 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: robobrowser==0.5.3 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages/robobrowser-0.5.3-py3.5.egg (from -r requirements.txt (line 2))
Requirement already satisfied: PyYAML==3.12 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml==3.6.4 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: beautifulsoup4>=4.3.2 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from robobrowser==0.5.3->-r requirements.txt (line 2))
Requirement already satisfied: six>=1.9.0 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from robobrowser==0.5.3->-r requirements.txt (line 2))
Requirement already satisfied: Werkzeug>=0.10.4 in /Users/lymanzhang/anaconda/lib/python3.5/site-packages (from robobrowser==0.5.3->-r requirements.txt (line 2))
```
I run the script, below is the information pop out of console.
```
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ cd kadenze-dl
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ ls
__pycache__		configuration.yml	helpers.py		kadenze-dl.py		kadenzeclient.py	progress.py		settings.py		test_app.py
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ python kadenze-dl.py
Signing in www.kadenze.com ...
Parsing course: creative-applications-of-deep-learning-with-tensorflow-iv
Parsing course: machine-learning-for-musicians-and-artists-v
lymanZHANGdeMacBook-Pro:kadenze-dl lymanzhang$ 
```
there still no any download happens.

My configuration.yml: 
```
kadenze:
    login: "***@gmail.com"
    password: "***"
download:
    resolution: "720"                     # Video definition to download. Valid values are "720" or "360".
    path: "/home/user/videos/kadenze"     # The absolute path to download to
    courses:                              # Courses to download, as they appear in the URL
            - "creative-applications-of-deep-learning-with-tensorflow-iv"
            - "machine-learning-for-musicians-and-artists-v"
```

**Comment by Gaarv** [comment]
Maybe make sure the download path you've set does exist (home/user/videos/kadenze) ? I'm abroad right now but will look into it in a few days when I get back, to see if anything changed on the site.

**Comment by lymanzhang** [comment]
thanks...

**Comment by ruiguo-bio** [comment]
I tried the script today, it does not work either. Maybe the website changed.

**Comment by Gaarv** [comment]
Thanks for the head up. It seems indeed that there is something preventing basic link parsing (probably JS) and we don't get the individual sessions links (with videos) as a result.

I think it should be possible to get around this, I will make some tests.

**Comment by Gaarv** [comment]
It was really a simple change, I doubt it was intentional at all :) Links to sessions are now available from a JSON string, like most of the content instead of HTML. I tested the change successfully but will wait on @lymanzhang confirmation on his issue, which was probably the cause.

**Comment by ruiguo-bio** [comment]
I have an issue
![screen shot 2017-03-28 at 11 03 50](https://cloud.githubusercontent.com/assets/20548903/24387191/43532a6a-13a6-11e7-8559-ed2d2731a5d0.png)

**Comment by Gaarv** [comment]
Looks like you haven't changed the placeholder / default download directory in the configuration file, creating anything in "/home/user" would require root privileges.

**Comment by ruiguo-bio** [comment]
Yes, I forgot to modify the new configuration file. It's ok after setting the folder.

**Comment by lymanzhang** [comment]
Wonderful! it works well.
thanks Gaarv a lot...

**Comment by lymanzhang** [comment]
```
Signing in www.kadenze.com ...
Parsing course: creative-applications-of-deep-learning-with-tensorflow-iv
Parsing session: introduction-to-tensorflow
[============================================================] 100.0% filename: 1.1_720.mp4
[============================================================] 100.0% filename: 1.2_720.mp4
[============================================================] 100.0% filename: 1.3_720.mp4
```

**Comment by Gaarv** [comment]
Cool, glad you got it working with the fix :) Thanks for reporting the issue !
