### ISSUE TITLE
install requirements out of date

### ISSUE THREAD

**Issue by vichug** [Gaarv/kadenze-dl#5]
while installing i had this message :

``
    DEPRECATION: Uninstalling a distutils installed project (lxml) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
``

i guess there is an option with pip to install only over a non-existent or an out-of-date version of a dependency, but i don't know it !

**Comment by Gaarv** [comment]
Hello,

It seems you installed requirements on a system that already had lxml installed, and issued that warning when replacing it with the one required.

It should not be a problem, however, if you had another application using that other version, it might not work anymore.

To get around this, you can use Anaconda https://www.continuum.io/downloads and a virtual environment:
(Linux / MacOS)
conda create -n kadenze python=3.5 pip
source activate kadenze
git clone https://github.com/Gaarv/kadenze-dl.git
cd kadenze-dl/
pip install -r requirements.txt
