### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by dev-lalit** [Gaarv/kadenze-dl#8]
there are some errors in helpers.py specifically in line 27 "courses
![screenshot 150](https://user-images.githubusercontent.com/18589570/40036226-cccfd78a-5823-11e8-940d-d8151b1280e5.png)
"

**Comment by dev-lalit** [comment]
Hello Gaarv , thank you and you have done a good job by making this. i find there is some issues while running in my system and i have tried to correct it for half an hour but not worked.can you suggest what to do?

**Comment by Gaarv** [comment]
Hello, 
Since it's basically parsing the pages code, it might be related to some change on the website. I will look if anything changed on kadenze.com and let you know.

**Comment by dev-lalit** [comment]
thank you so much.good job sir keep it up.

**Comment by Gaarv** [comment]
The json attribute was changed from "courses" to "my_courses". I ran only a quick download, it seems nothing else was changed. I commited the change, so you can test if that solve the issue.

I will get more download done at home on a faster connection to make sure :)

**Comment by dev-lalit** [comment]
thank you for your help Gaarv. it worked , thank you so much again.

**Comment by Gaarv** [comment]
No problem, you're welcome !
